import Navbar from "../components/Navbar"

// Revisar documentacion: Nextjs metadata
export const metadata = {
  title: 'Tienda con Next.js',
  description: 'Generated by Next.js',
  keywords: "tienda, online, ecommerce",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
