import Navbar from "../components/Navbar"
import { Roboto } from 'next/font/google'

// Revisar documentacion: Nextjs metadata
export const metadata = {
  title: 'Tienda con Next.js',
  description: 'Generated by Next.js',
  keywords: "tienda, online, ecommerce",
}

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  style: ["italic", "normal"],
  subsets: ["latin"],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
